version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: babel-plugin-date-fns
    versions:
    - ">= 2.a, < 3"
  - dependency-name: eslint-plugin-redux-saga
    versions:
    - "> 0.10.0"
  - dependency-name: extract-css-chunks-webpack-plugin
    versions:
    - ">= 4.a, < 5"
  - dependency-name: redux-saga
    versions:
    - ">= 1.a, < 2"
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: serialize-error
    versions:
    - 8.0.0
    - 8.0.1
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: ramda
    versions:
    - 0.27.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.2.0
  - dependency-name: html-loader
    versions:
    - 1.3.2
  - dependency-name: terser-webpack-plugin
    versions:
    - 4.2.3
    - 5.1.1
  - dependency-name: url-loader
    versions:
    - 4.1.1
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 19.0.1
    - 26.0.1
  - dependency-name: which
    versions:
    - 2.0.2
