language: node_js
node_js:
  - 10
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
before_script:
  - yarn build
script:
  - yarn test
after_script:
  - yarn count
